Repository callumrollo/erddaplogs, pull requests merged in 2024-05, with the labels that each got.

#17 Use a user agent library
  .gitignore
  env.yml
  logparse.py
Labels: enhancement, ioos-code-sprint-2024

#18 add example nginx logs
  .gitignore
  example_data/nginx_example_logs/tomcat-access.log.1
  example_data/nginx_example_logs/tomcat-access.log.2
  example_data/nginx_example_logs/tomcat-access.log.3
  example_data/nginx_example_logs/tomcat-access.log.4
  example_data/nginx_example_logs/tomcat-access.log.5
  example_data/nginx_example_logs/tomcat-access.log.6
  example_data/nginx_example_logs/tomcat-access.log.7
  example_data/nginx_example_logs/tomcat-access.log.8
  example_data/nginx_example_logs/tomcat-access.log.9
  weblogs-parse-demo.ipynb
Labels: enhancement, ioos-code-sprint-2024

#21 docs: add docstrings to methods and funcs
  logparse.py
  plot_funtions.py
Labels: documentation, ioos-code-sprint-2024

#23 add columns for erddap request type and dataset id
  plot_funtions.py
  weblogs-parse-demo.ipynb
Labels: enhancement, ioos-code-sprint-2024

#28 lint all files with pre-commit
  .pre-commit-config.yaml
  erddaplogs/logparse.py
  erddaplogs/plot_functions.py
  requirements-dev.txt
Labels: ioos-code-sprint-2024

#29 Remove email addresses
  erddaplogs/logparse.py
Labels: bug, ioos-code-sprint-2024

#31 test plotting functions and fix warnings
  erddaplogs/logparse.py
  erddaplogs/plot_functions.py
  tests/test_erddap_logs.py
Labels: enhancement, ioos-code-sprint-2024

#32 fix plot bug and create test grid
  .github/workflows/tests.yml
  erddaplogs/plot_functions.py
  tests/test_erddap_logs.py
Labels: bug, ioos-code-sprint-2024

#38 Second try at fixing issue #9 after rebasing.
  erddaplogs/logparse.py
Labels: bug, ioos-code-sprint-2024

#41 Pull in data from datasets.xml
  erddaplogs/logparse.py
  example_data/datasets.xml
  tests/test_erddap_logs.py
  weblogs-parse-demo.ipynb
Labels: enhancement, ioos-code-sprint-2024

#50 tests for anonymized data
  tests/test_erddap_logs.py
Labels: enhancement, ioos-code-sprint-2024
